tpr/tpr.go
used to determine the interval at which the lister function is called
Towards #13.
=> add ResyncPeriod constant

tpr/error.go, tpr/kind.go, tpr/kind_test.go, tpr/tpr.go, tpr/tpr_test.go
Towards https://github.com/giantswarm/giantswarm/issues/1483
This change allows passing full name of TPR and extract kind name and group name from it. This is useful for creating TPOs (used in kubernetesd), and also allows creating REST endpoints (used in all operators, and potentially in reconciliation loop).
Next steps is to add pluralization logic and provide methods with TPR resource endpoint and TPR watch endpoint.
=> Infer TPR kind and group

tpr/error.go, tpr/kind.go, tpr/kind_test.go, tpr/tpr.go
In operators we log when resource already existed.
TODO: update cert-operator
=> Respond with alreadyExists in TPR.Create*

tpr/decoder.go, tpr/tpr.go
The decoder should reuse json.Decoder instead of creating one on every
Decode call.
=> fix stream decoder

client/k8s/k8s.go, client/k8s/k8s_test.go
IMO whenever configuration is provided we should always provide a way of gathering default configuration. This eases development, testing and ensures package specific configuration is given on purpose by the maintainer, because he knows the package best. I as a user do not want to care about all the little details all the times. This PR adds a `DefaultConfig` method to the k8s client package, which should always be used whenever a new client is initialized.
=> added DefaultConfig for k8s client

glide.lock, glide.yaml
This is to avoid conflicts and make vendor updates experience smoother.
=> pin go-restful

framework/metricsresource/camel_case.go, framework/metricsresource/camel_case_test.go, framework/metricsresource/resource.go
This PR prevents the following panic. We recently added the metrics resource which is configured with the name of the operator. The operators have dashes in their names which Prometheus does not like as namespace/subsystem. 
```
panic: descriptor Desc{fqName: "ingress-operator_configmap_operatorkit_framework_operation_duration_milliseconds", help: "Time taken to process a single reconciliation operation.", constLabels: {}, variableLabels: [operation]} is invalid: "ingress-operator_configmap_operatorkit_framework_operation_duration_milliseconds" is not a valid metric name
goroutine 1 [running]:
github.com/giantswarm/ingress-operator/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420012ec0, 0xc4202d7d10, 0x1, 0x1) …
```
=> ensure Prometheus namespace and subsystem are camel case

framework/cancelercontext/canceler_context.go, framework/framework.go, framework/framework_test.go
This PR provides resource cancelation using the context dispatched through the resource steps being processed. For a discussion around the initial motivation see also https://gigantic.slack.com/archives/C2MS2VB37/p1505483832000091. See also https://github.com/giantswarm/kvm-operator/pull/182.
=> added resource cancelation support

framework/framework.go, framework/framework_initializer_test.go
The initializer is necessary to get the inter resource communication right. See how it is used in https://github.com/giantswarm/kvm-operator/pull/197.
=> added initializer to reconciler framework for custom context setup

context/deletionallowedcontext/deletion_allowed_context.go, context/deletionallowedcontext/deletion_allowed_context_test.go
This PR adds a new context package to have a mechanism to decide if the deletion of resources is allowed or not. We have this already for updates. I am currently working on the cert-operator where PKI backend resources are not allowed to be deleted when single certificates are deleted. Note that I created a new top level directory `context`. I would like to move the other context packages there as well to free the framework package. I would do this in a next step separately.
=> added deletionallowedcontext package

framework/framework.go, framework/framework_test.go
I merged the former PR because CI was green. Architect is not building nor testing operatorkit right now.
=> fix import path

framework/framework.go, informer/informer.go
See https://github.com/giantswarm/architect/pull/165
```
2017/10/16 10:42:37 running task: go-vet:	'docker run --rm -v /Users/joseph/go/src/github.com/giantswarm/operatorkit:/go/src/github.com/giantswarm/operatorkit -e GOPATH=/go -w /go/src/github.com/giantswarm/operatorkit quay.io/giantswarm/golang:1.9.1 go vet ./...'
framework/framework.go:314: unreachable code
exit status 1
informer/informer.go:314: unreachable code
informer/informer.go:397: unreachable code
exit status 1
2017/10/16 10:42:54 could not execute workflow: exit status 1
```
=> Removes unreachable code

framework/framework.go, framework/framework_initializer_test.go, framework/framework_test.go, framework/patch.go, framework/resource/logresource/resource.go, framework/resource/logresource/resource_test.go, framework/resource/metricsresource/resource.go, framework/resource/metricsresource/resource_test.go, framework/resource/retryresource/resource.go, framework/resource/retryresource/resource_test.go, framework/spec.go
As we noticed in our operators we often do not really need update, or
want to postpone implementation. E.g. we do not support rolling
certificates, but we want to add that feature later. This require being
able to specify that update part should not be invoked by the framework.
Introduction of Patch struct is a solution to that problem. Create,
Delete and Update functions are called by the framework only when patch
has corresponding parts set.
The Patch is computed in similar way to previous GetUpdateState
function, which is now NewUpdatePatch. NewUpdatePatch function creates
a Patch object when CRO is created or updated. There is also
NewDeletePatch function which is called when CRO is deleted. Both
NewUpdatePatch and NewDeletePatch create Patch struct which in turn is
processed by …
=> framework: compute patch in a single step

tpr/tpr.go, tpr/tpr_test.go
This will make test environments where the kubernetes-api is started up along with services that want to talk to it right away more reliable.
=> Add retry on creating the tpr as well

framework/resource/logresource/resource.go
Fixes https://github.com/giantswarm/operatorkit/issues/90
This is for completeness. When I was watching logs it felt strange there is no log on error.
=> logresource: log action=error on error

framework/framework.go, framework/framework_test.go
Fixes a problem I had earlier with aws-operator crash looping from a panic because the Patch was nil. The resource now returns an empty Patch struct but I think the framework should handle this. WDYT?
See https://github.com/giantswarm/aws-operator/pull/495
=> Handle nil Patch in ProcessUpdate and ProcessDelete

framework/backoff_factory.go, framework/framework.go, framework/framework_initializer_test.go, informer/informertest/informertest.go, informer/informertest/informertest_test.go, informer/spec.go, tpr/spec.go, tpr/tprtest/tpr_test.go, tpr/tprtest/tprtest.go
This PR aims to get rid of some boilerplate code we have to carry around in the operator projects to setup the framework. See https://github.com/giantswarm/kvm-operator/pull/244 where this PR is used.
=> unify operator bootstrap magic

framework/framework.go, framework/metric.go
It would be cool to be able to get metrics for the event processing durations. In theory you can already get metrics that are pretty close to the metrics introduced here, but only if you wrap your own resources with the metrics resource. I assume not everybody is doing that or knows about it so I thought it would be good to have a common way of having the overall histogram information of how long delete and update events take. Note that one weird thing is that the update event channel also handles the actual create events. This is because our informer merges create and update events for reasons. WDYT?
=> added histogram observations for framework event processing

client/k8sclient/k8sclient.go, client/k8sextclient/k8sextclient.go
Fixes #96 
Allows specifying TLS certs as raw bytes as well as files. The cert data config takes precedence over cert files and this is described in the GoDoc.
=> Allow specifying certificates as raw bytes

client/k8scrdclient/k8scrdclient.go, framework/framework.go
Note this goes into `kubernetes-1.7`.
=> backported CRD client advances for use in tools still being behing

framework/crud_resource.go
This resource implements interface:
type I interface {
EnsureCreated(ctx context.Context, obj interface{}) error
EnsureDeleted(ctx context.Context, obj interface{}) error
}
It isn't used anywhere now. The ultimate goal is to replace current
Resource interface with interface above and have an option to switch to
complex CRUDResource.
- - -
It originated in https://github.com/giantswarm/node-operator/pull/6#discussion_r165577687
I also consider using it in some of azure-operator resources as well, where SDK provides CreateAndUpdate functions which are idempotent.
=> framework: add CRUDResource

framework/crud_resource.go, framework/crud_resource_ops.go, framework/resource/internal/wrapper.go, framework/resource/metricsresource/resource.go, framework/resource/metricsresource/resource_test.go, framework/resource/retryresource/resource.go, framework/resource/retryresource/resource_test.go, framework/spec.go
I noticed we don't need the Underlying method in the Resource interface, as we
can handle underlying internally in wrapping resources by checking if they
implement Wrapper interface. From the user perspective this is less confusing.
And also makes it easier to implement wrapping resources for the new WIP CRUDResource.
=> framework: remove Underlying from Resource interface

framework/resource_router.go
I discovered a problem with the resource routing in https://github.com/giantswarm/aws-operator/pull/795. There we introduce multiple frameworks in order to have different resync periods for different resources. Now it can just happen that a framework has for instance only one resource set with a new version and all old versions will just not be managed by the framework. This means the errors we see are not valid, which means removing the error should be the way to go. We could also add some logging actually. Opinions welcome. 
```
{"caller":"github.com/giantswarm/aws-operator/vendor/github.com/giantswarm/operatorkit/framework/framework.go:162","event":"update","function":"UpdateFunc","level":"error","message":"stop framework reconciliation due to …
```
=> allow missing resource set

framework/framework.go
They aren't methods of the framework so are moved to the bottom.
=> framework: move Process{Delete,Update} in the file

informer/metric.go
I was checking on some metrics for our informer and noticed something is missing. I don't know how this could happen but lets maybe register the metrics we tried to collect already. Should help identifying issues in operator memory usage.
=> actually registers defined metric

framework/finalizer.go
Very minor change, this is necessary if multiple frameworks watch the same object. It was not clear which finalizer was missing beforehand.
=> Add framework name to log output for finalizers

framework/resource.go, framework/resource_set.go
Add an explicit note about `Resource` execution order to `framework.ResourceSetConfig` as well.
=> Improve comments/gdoc on resource execution order

framework/integration/test/reconciliation/backoff.go, framework/integration/test/reconciliation/error.go, framework/integration/test/reconciliation/reconciliation_test.go
This is a simple change that caused flakyness in the test that will need a little bit of explaining:
The framework is configured to reconcile every 10 seconds. This tests counts how often the resource functions of the framework have been called and checks if that's correct.
This test always waits a set amount of time before the check, this was 25 seconds. So 5 seconds to do the operation (add or delete an object) with a lot of room for safety and then two reconciliation periods.
So the overall time it ran was 2*25 + test execution time = 50 to 51 seconds. This lead to the problem: if execution was a little slower but the framework executed very quickly, then it could reconcile 5 times in roughly 51 seconds the test ran. This would cause the test to fail.
So I reduced the wait each time by …
=> Fix flakyness in reconciliation integration testcase

controller/controller.go, controller/finalizer.go
Towards https://github.com/giantswarm/giantswarm/issues/3110.
=> removes finalizer in case no resource set handles the runtime object

example/memcached-operator/controller/memcached.go
Adds comments to the controller wiring code in the example operator. To help with the understanding of the example.
=> Add extra comments for controller wiring in example operator

controller/controller.go, controller/error.go, controller/finalizer.go
While developing I noticed there is a nasty case which we actually expect but it is hard to identify. The REST client configured for the controller has to be of a specific kind. This PR is an attempt to make the error more obvious and get to know about the error faster. 
```
{"caller":"github.com/giantswarm/kvm-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:298","event":"update","level":"error","message":"stop reconciliation due to error","object":"/apis/provider.giantswarm.io/v1alpha1/namespaces/default/kvmconfigs/n2ywy","stack":"[{/go/src/github.com/giantswarm/kvm-operator/vendor/github.com/giantswarm/operatorkit/controller/finalizer.go:74: } {/go/src/github.com/giantswarm/kvm-operator/vendor/github.com/giantswarm/operatorkit/controller/finalizer.go:43: } {no …
```
=> panics when invalid REST client configured

controller/controller.go, controller/error.go, controller/error_test.go
When controller doesn't have RBAC rule for CRD, apimachinery emits
StatusError with Reason: Forbidden. This adds matching against this and
transforms error to statusForbiddenError with user friendly error
message.
An example of log message:
```
{"caller":"github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:249","level":"warning","message":"retrying event processing due to error","stack":"[{/home/tuommaki/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:241: } {/home/tuommaki/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:454: controller might be missing RBAC rule for clusternetworkconfigs.core.giantswarm.io …
```
=> Add error matching for apimachinery StatusError

README.md, docs/troubleshooting.md
Purpose of this guide is to document common mistakes that are easy to
make accidentally but hard to debug due to lack of informative error
messages.
Pitfalls listed here are stumbled on once in a while and often it might
take considerable time for multiple developer to figure out what's wrong
when error message is not perfectly clear. Therefore having a central
place to look for common mistakes as a first aid can be useful and save
time.
=> Add initial version of troubleshooting guide

informer/collector.go
> Hello monitoring folks. I want to add some metrics to the `node-operator` and wonder why and which way to go. I think it would be good to have metrics about drainer configs timing out. I fear this is a bit like the error threshold issue but maybe you can push me into the right direction. 
See 
- https://gigantic.slack.com/archives/C0E0V16DC/p1531477311000351
- https://github.com/giantswarm/node-operator/blob/e6adce72d2a3b15238237e60299709433724ac4d/service/controller/v1/resource/drainer/create.go#L50-L67
=> adds creation timestamp to informer metrics

controller/integration/test/basic/basic_test.go, controller/integration/test/controlflow/controlflow_test.go, controller/integration/test/parallel/parallel_test.go, controller/integration/wrapper/configmap/crud.go, controller/integration/wrapper/configmap/error.go, controller/integration/wrapper/nodeconfig/crud.go, controller/integration/wrapper/nodeconfig/error.go
Earlier I fucked this up when masking errors. The tests were not aligned with our error handling from the get go. This should be sorted now.
=> fixes error handling in e2e tests

informer/informer.go, informer/metric.go
Towards https://github.com/giantswarm/giantswarm/issues/4518. Idea here is to have a metric we can alert on that tells us when the cache update was not done for some time. I will also sort out the alert.
=> adds metrics for time of last updated informer cache

Gopkg.lock, Gopkg.toml, README.md, controller/controller.go, controller/finalizer.go, controller/integration/test/parallel/error.go, controller/integration/test/parallel/parallel_test.go, controller/integration/test/reconciliation/error.go, controller/integration/test/reconciliation/reconciliation_test.go, controller/string_cache.go, vendor/github.com/patrickmn/go-cache/CONTRIBUTORS, vendor/github.com/patrickmn/go-cache/LICENSE, vendor/github.com/patrickmn/go-cache/README.md, vendor/github.com/patrickmn/go-cache/cache.go, vendor/github.com/patrickmn/go-cache/sharded.go
Fixes https://github.com/giantswarm/giantswarm/issues/4572.
With this merged there should be always only one successful deletion reconciliation per object per controller.
=> controller: inhibit deletion events for controller w/o finalizer

controller/controller.go, controller/integration/test/controlflow/controlflow_test.go, controller/integration/test/error/error_test.go, controller/integration/test/parallel/parallel_test.go, controller/integration/test/reconciliation/reconciliation_test.go, controller/integration/test/statusupdate/status_update_test.go, example/memcached-operator/main.go, informer/informer.go
Towards https://github.com/giantswarm/giantswarm/issues/5043. This PR contains a **breaking change** for the controller boot API. It now takes an additional context, where it before did not take any argument. When you run into compile issues, just pass `ctx` to [`Controller.Boot`](https://godoc.org/github.com/giantswarm/operatorkit/controller#Controller.Boot).
=> improves connection management

controller/controller.go
@xh3b4sd noticed there are missing loops, e.g. we have logs with
"loop":"25" and "loop":"27" but no logs with "loop":"26". In some rare
cases we see that controller stops reconciling. We need more diagnostic
information.
=> controller: add more logs around event processing

README.md, docs/file_structure.md
Follow up to https://github.com/giantswarm/chart-operator/pull/200#issuecomment-465210850.
Just covers the resource file structure for now. We can extend later to controllers etc if that's needed.
=> Add docs for operatorkit resource file structure

client/k8srestconfig/k8s_rest_config.go
giantswarm/operatorkit/client/k8srestconfig/k8s_rest_config.go:120: cannot use k8srestconfig.Config.InCluster and %!T(MISSING).KubeConfig} {invalid config error}]
=> k8srestconfig: fix string format

docs/metrics_provider.md
Fix a typo, adjust a sentence so it read a bit clearer (for me at least)
=> Fix a typo in documentation.

controller/controller.go, controller/controller_test.go
Construction of new context when updating existing one creates a memory leak
because internal implementation of reflect.WithValue() uses reflect.valueCtx
that is essentially a linked list. Therefore construction of new context on
value setting effectively adds a new element to this list and therefore creates
a memory leak when called e.g. in loop.
With this change the new context is only created when existing context doesn't
contain loggermeta context value.
Towards https://github.com/giantswarm/giantswarm/issues/6416
Replaces https://github.com/giantswarm/operatorkit/pull/305
=> Don't construct new context when updating existing one

resource/k8s/configmapresource/create.go, resource/k8s/configmapresource/delete.go, resource/k8s/configmapresource/patch.go, resource/k8s/configmapresource/update.go, resource/k8s/secretresource/create.go, resource/k8s/secretresource/delete.go, resource/k8s/secretresource/patch.go, resource/k8s/secretresource/update.go
Using the common resources I noticed deletion does not work as expected during delete events. Objects are not deleted. Checking the code we generate the same patches for update and delete events. This PR keeps the update patches as they are and I assume these are fine. We only change the delete patches as such that we simply delete what we get with the current state.
=> fix resource deletion

controller/controller.go, controller/controller_cancel_crud_test.go, controller/controller_cancel_test.go, controller/integration/test/controlflow/controlflow_test.go, controller/integration/test/error/error_test.go, controller/integration/test/parallel/parallel_test.go, controller/integration/test/reconciliation/reconciliation_test.go, controller/integration/test/statusupdate/status_update_test.go, controller/integration/testresourceset/resource_set.go, controller/integration/wrapper/configmap/wrapper.go, controller/integration/wrapper/drainerconfig/wrapper.go, controller/patch_no_panic_test.go, controller/resource_set.go, example/memcached-operator/controller/memcached.go, example/memcached-operator/controller/simple_resource_router.go
Based on [`move-crud-resource`](https://github.com/giantswarm/operatorkit/pull/310). Here we start to use the new resource interface in the `controller` package.
=> use new resource interface in controller package

controller/controller.go, controller/controller_cancel_crud_test.go, controller/controller_cancel_test.go, controller/crud_resource.go, controller/crud_resource_ops.go, controller/crud_resource_patch_dispatch_test.go, controller/integration/test/controlflow/controlflow_test.go, controller/integration/test/error/error_test.go, controller/integration/test/parallel/parallel_test.go, controller/integration/test/reconciliation/reconciliation_test.go, controller/integration/test/statusupdate/status_update_test.go, controller/integration/testresourceset/resource_set.go, controller/integration/wrapper/configmap/wrapper.go, controller/integration/wrapper/drainerconfig/wrapper.go, controller/patch.go, controller/patch_no_panic_test.go, controller/resource_set.go, controller/spec.go, example/memcached-operator/controller/memcached.go, example/memcached-operator/controller/simple_resource_router.go, resource/crud/error.go, resource/crud/patch.go, resource/crud/resource.go, resource/crud/resource_test.go, resource/crud/spec.go, resource/spec.go
We would like to drive a better project and code structure forward. Since we have the `resource` package we should move more resource related code in there and free the `controller` package from it. There are more refactorings and improvements we can do but for now this should be one first step. The change does not break APIs. Code should start to transition towards using the new code locations though.
=> move crud resource to resource package

client/k8scrdclient/k8scrdclient.go
Toward https://github.com/giantswarm/giantswarm/issues/7299
SInce `Status` subresource is a part of spec, we should update it through `.Update` function. 
Already tested in `centaur/h0cg9`
=> Update subresource by update function

controller/controller.go
We are not cleaning the resource key after finishing the looping each resource, so sometimes logs are hard to understand as it indicated some resources. 
For instance, 
```
D 10/22 13:45:23 /apis/application.giantswarm.io/v1alpha1/namespaces/giantswarm/charts/aqua-app-enforcer statusv1 reconciling object | operatorkit/controller/controller.go:295 | controller=chart-operator-chart | event=update | loop=79 | version=13500
```
This is obviously `controller` stack, but it shows the log itself like from `resource` perspective. 
By this change, we would no longer see the dangling `resource` key in the context.
=> Clear resource in context in each loop.

controller/error.go
Toward https://github.com/giantswarm/giantswarm/issues/7313
In some cases, errors related to port-forward have a different sentence that we are expecting, 
```
E 10/31 07:05:38 /apis/application.giantswarm.io/v1alpha1/namespaces/giantswarm/charts/aqua-app-server statusv1 caught third party runtime error | operatorkit/controller/controller.go:429 | controller=chart-operator-chart | event=update | loop=1057 | stack=&errors.errorString{s:"error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:37325->127.0.0.1:48982: write tcp4 127.0.0.1:37325->127.0.0.1:48982: write: broken pipe"} | version=1023827
```
See `copying from remote stream to local connection`.
Currently, we only compare it with `error copying from local connection to remote stream` so it does not regard it …
=> Checking port-forwarding error as reverse order

client/k8scrdclient/k8scrdclient.go, client/k8srestconfig/k8s_rest_config.go
We want to use github.com/giantswarm/k8sclient in `operatorkit`. Right now `k8sclient` imports `operatorkit`. The idea is to move the client package to `k8sclient` and sort out the dependency graph. I will follow up with a PR in `k8sclient`.
=> deprecate client package

controller/controller.go
Toward giantswarm/giantswarm#8129
We need to compare the labels before controller handles events. If the operator watch the k8s resource rather than k8s, we can use this logic to reduce the noise in logs.
=> Filter labels before it pass to controller

controller/controller.go, controller/integration/test/basic/basic_test.go
I believe we no longer use the `UpdateFunc()` and `DeleteFunc()`, so they are not required anymore. I tried adapting the basic test that was using these functions, to use `Reconcile` instead.
=> Call the new Reconcile method

flag/service/kubernetes/kubernetes.go
When configuring k8sclient in operators, one may either specify path to kubectl
configuration file or fill parameters for restconfig.
=> Add flag for kubeconfig file path

Gopkg.lock, controller/controller.go, vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go, vendor/sigs.k8s.io/controller-runtime/pkg/builder/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go, vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go, vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go, vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Studying our codebase and some of our dependencies I found out that there is a package builder in the controller-runtime library:
> Package builder wraps other controller-runtime libraries and exposes simple patterns for building common Controllers.
This PR uses the builder instead of doing the wiring ourselves, however it should be functionally the same. Kubebuilder uses this builder under the hood.
=> Use controller-runtime Controller builder

Gopkg.lock, Gopkg.toml, vendor/github.com/giantswarm/k8sclient/Gopkg.lock, vendor/github.com/giantswarm/k8sclient/Gopkg.toml, vendor/github.com/giantswarm/k8sclient/k8scrdclient/k8scrdclient.go, vendor/github.com/giantswarm/micrologger/CHANGELOG.md
We need to pin the micrologger dependency to the v0.1.0 version which is the one using dep instead of newer versions that use go modules.
=> Use micrologger v0.1.0

CHANGELOG.md, controller/collector/set.go, controller/collector/timestamp.go, controller/controller.go, controller/controller_test.go
Checking in on https://github.com/giantswarm/giantswarm/issues/10553 we noticed we actually have a problem with collector registrations when running multiple controllers in one operator. The best way to sort this out for us was now to define constant labels for the controller running the collector. There is also a minimal unit test proving that it works. Using the same name makes the test panic. 
```
--- FAIL: Test_Controller_Collector_Register (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
panic: duplicate metrics collector registration attempted
goroutine 47 [running]:
testing.tRunner.func1.1(0x208cee0, 0xc00052c1a0)
/Users/xh3b4sd/.gvm/gos/go1.14.1/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc00051f7a0) …
```
=> fix metrics registration via unique constant labels

docs/metrics_provider.md
Based on what we learned so far it is better to separate operator and collector. A good example is our `azure-operator`. Based on https://gigantic.slack.com/archives/C2MS2VB37/p1596201674467600 we agree on this so we just write it down here now.
=> improve collector docs based on recent advances

CHANGELOG.md, pkg/controller/controller.go
At some points, we need to bind the controller to a specific namespace. This change is to set the namespace from the controller generator. 
Slack conversation: https://gigantic.slack.com/archives/C2MS2VB37/p1606222861091500
=> Add namespace in config & and wired it to manager

go.mod, go.sum, pkg/controller/controller.go, pkg/controller/finalizer.go, pkg/resource/k8s/configmapresource/create.go, pkg/resource/k8s/configmapresource/delete.go, pkg/resource/k8s/configmapresource/update.go, pkg/resource/k8s/secretresource/create.go, pkg/resource/k8s/secretresource/delete.go, pkg/resource/k8s/secretresource/update.go, pkg/resource/wrapper/retryresource/basic_resource.go, pkg/resource/wrapper/retryresource/crud_resource.go
Changed using this script:
```
devctl replace -i \
'LogCtx\(ctx, "level", "debug", "message", fmt.Sprintf\((.*)\)\)' \
'Debugf(ctx, $1)'\
'**/*.go'
devctl replace -i \
'LogCtx\(ctx, "level", "debug", "message", "(.*)"\)' \
'Debugf(ctx, "$1")'\
'**/*.go'
devctl replace -i \
'LogCtx\(ctx, "level", "error", "message", "fmt.Sprintf\((.*)\)", "stack", microerror.JSON\(err\)\)' \
'Errorf(ctx, err, $1)'\
'**/*.go'
devctl replace -i \
'LogCtx\(ctx, "level", "error", "message", "(.*)", "stack", microerror.JSON\(err\)\)' \
'Errorf(ctx, err, "$1")'\
'**/*.go'
devctl replace -i \
'r.logger.LogCtx\(ctx, "level", "warning", "message", "retrying due to error", "stack", microerror.JSON\(err\)\)' \
'r.logger.Errorf(ctx, err, "retrying due to error")' \
'**/*.go'
goimports -local …
```
=> Use micrologger@v0.4.0 Debugf/Errorf

CHANGELOG.md, pkg/controller/controller.go, pkg/controller/internal/sentry/default.go, pkg/controller/internal/sentry/service.go
Added `SentryTags` Config field to allow setting custom tags to be sent alongside errors to `sentry.io`.
=> Expose settings for sentry client

CHANGELOG.md, pkg/controller/controller.go
This was moved in https://github.com/giantswarm/operatorkit/pull/496 in order to remove a circular dependency, but some external callers still rely on it.
=> Re-expose NewSelector in controller

CHANGELOG.md, go.mod, go.sum, pkg/resource/k8s/configmapresource/new_config_map_to_update.go, pkg/resource/k8s/configmapresource/resource.go, pkg/resource/k8s/configmapresource/update.go
Towards https://github.com/giantswarm/giantswarm/issues/14163
Extends the generic configmap resource to configure a list of allowed labels.
This is needed in the clusterconfigmap in cluster-operator because the configmap includes the label below which is added by app-operator so it can watch for changes.
```
labels:
app-operator.giantswarm.io/watching: "true"
```
=> Add AllowedLabels to configmap resource

CHANGELOG.md, pkg/controller/controller.go, pkg/controller/metric.go
Currently `operatorkit_controller_error_total` doesn't include the name of the controller associated.
in [PMO](https://github.com/giantswarm/prometheus-meta-operator) we have many controllers bundled.
We need to distinguish total errors per controller, to build alerts
=> Include controller name as label in reconcileErrors metric
