giantswarm/operatorkit

glide.lock
glide.yaml
secret/cert/cert.go
secret/cert/error.go
vendor/github.com/giantswarm/certificatetpr/.gitignore
vendor/github.com/giantswarm/certificatetpr/LICENSE
vendor/github.com/giantswarm/certificatetpr/README.md
vendor/github.com/giantswarm/certificatetpr/circle.yml
vendor/github.com/giantswarm/certificatetpr/custom_object.go
vendor/github.com/giantswarm/certificatetpr/glide.lock
vendor/github.com/giantswarm/certificatetpr/glide.yaml
vendor/github.com/giantswarm/certificatetpr/list.go
vendor/github.com/giantswarm/certificatetpr/name.go
vendor/github.com/giantswarm/certificatetpr/spec.go
vendor/github.com/giantswarm/certificatetpr/tls_assets.go
vendor/github.com/giantswarm/certificatetpr/tls_assets_test.go
vendor/github.com/giantswarm/microkit/server/codes.go
vendor/github.com/giantswarm/microkit/server/response_error.go
vendor/github.com/giantswarm/microkit/server/response_writer.go
vendor/github.com/giantswarm/microkit/server/server.go
vendor/github.com/giantswarm/microkit/server/spec.go
vendor/github.com/giantswarm/microkit/storage/etcd/service.go
vendor/github.com/giantswarm/microkit/validator/helpers.go
vendor/github.com/giantswarm/microkit/validator/helpers_test.go
vendor/github.com/giantswarm/microkit/validator/immutable_attribute.go
vendor/github.com/giantswarm/microkit/validator/immutable_attribute_test.go
vendor/github.com/giantswarm/microkit/validator/unknown_attribute.go
vendor/github.com/giantswarm/microkit/validator/unknown_attribute_test.go

This goes towards abstraction of operator code. The AWS operator already uses this code. I slightly modified it, but in the essence it stays the same. Soon the KVM operator wants to use this as well. WDYT?

added secret watcher for general abstraction between operators

---

tpr/error.go
tpr/tpr.go
tpr/tpr_test.go
util/retry.go

As of right now allows only creating the TPR and waiting till it's
ready.
Towards https://github.com/giantswarm/cert-operator/issues/44.

Add initial TPR abstraction

---

operator/operator.go
operator/spec.go

We came up with the operator framework/guideline/interface in the ingress-operator. It belongs to here. I am only not sure where to put it. Feedback please.

added operator package for operator framework

---

operator/operator.go
operator/spec.go

Towards https://github.com/giantswarm/giantswarm/issues/1526.

do not invoke deletion in creation events

---

framework/error.go
framework/operator.go
framework/operator_test.go
framework/spec.go

Towards https://github.com/giantswarm/operatorkit/pull/37.

renamed operator package to framework package

---

framework/error.go
framework/operator.go
framework/operator_test.go

Towards https://github.com/giantswarm/operatorkit/pull/37.

made framework a configurable service

---

framework/framework.go
framework/framework_test.go
framework/logresource/resource_test.go
framework/metricsresource/resource_test.go
framework/retryresource/resource_test.go

Fixes https://github.com/giantswarm/giantswarm/issues/1839. See also https://github.com/giantswarm/kvm-operator/pull/177 where this change is used.

added event handler to manage add/delete/update functions

---

framework/framework.go
framework/framework_test.go
framework/logresource/resource.go
framework/logresource/resource_test.go
framework/metricsresource/resource.go
framework/metricsresource/resource_test.go
framework/retryresource/resource.go
framework/retryresource/resource_test.go
framework/spec.go

This PR adds a context to the reconciler framework.

added context to reconciler framework

---

framework/framework.go

Fixes https://github.com/giantswarm/operatorkit/issues/62.

better log structure

---

framework/framework.go
framework/framework_initializer_test.go
framework/resource_router.go

Towards https://github.com/giantswarm/giantswarm/issues/2007.

added configurable resource router

---

informer/informer.go

As discussed here: https://github.com/giantswarm/operatorkit/pull/121#pullrequestreview-79145972

informer: update defaults to 1s/5m

---

client/k8scrdclient/error.go
client/k8scrdclient/k8scrdclient.go

moved crd client to client dir

---

client/k8srestconfig/error.go
client/k8srestconfig/k8s_rest_config.go

This is a cure for that: https://github.com/giantswarm/kvm-operator/blob/01b6d2a67e06af04bb642de98bd77304b59d8bdd/service/framework.go#L249-L277

k8srestconfig: add

---

client/k8scrdclient/k8scrdclient.go
framework/framework.go

This PR will help in integration tests where we need to setup and teardown.

added deletion support for CRDs

---

framework/framework.go
framework/resource/retryresource/resource.go
framework/resource_set.go

Some boyscouting from my side. There are open PRs working with retry resources and such where logging should be aligned as well. When this here is fine I would like to get this straight in other PRs as well and I will provide more PRs for this then.

improved log structure

---

framework/error.go
framework/framework.go
framework/resource_router.go

Towards https://github.com/giantswarm/operatorkit/pull/164#discussion_r171312648.

polish error naming

---

.circleci/config.yml
framework/finalizer.go

Towards https://github.com/giantswarm/giantswarm/issues/1595
Should be pretty straight forward, integration tests seem to work in parallel now.

Align circle config

---

.circleci/config.yml
.gitignore
framework/integration/test/reconciliation/reconciliation_test.go

Adding some basic structure first, so it shows in circle right away - actual implementation of the testcase coming next.
towards https://github.com/giantswarm/giantswarm/issues/1595

Add empty testcase for reconciliation

---

framework/crud_resource.go
framework/framework.go
framework/resource_set.go

Tests to come later. This is a quick fix.

framework: fix resourcecanceledcontext

---

controller/controller.go
controller/finalizer.go

Towards https://github.com/giantswarm/giantswarm/issues/2993.

prevents finalizers from being removed when reconciliation got canceled

---

.circleci/config.yml
.gitignore
controller/integration/test/controlflow/backoff.go
controller/integration/test/controlflow/controlflow_test.go
controller/integration/test/controlflow/error.go
controller/integration/testresource/error.go
controller/integration/testresource/testresource.go

towards https://github.com/giantswarm/giantswarm/issues/1595

Add integration test to check that errors during deletion do not remove finalizer

---

controller/context/finalizerskeptcontext/finalizers_kept_context.go
controller/context/finalizerskeptcontext/finalizers_kept_context_test.go
controller/controller.go
controller/resource_set.go

Towards https://github.com/giantswarm/giantswarm/issues/2993.

adds primitive to keep finalizers on demand

---

controller/controller.go
controller/integration/wrapper/configmap/wrapper.go
controller/integration/wrapper/nodeconfig/wrapper.go
informer/collector.go
informer/error.go
informer/informer.go
informer/spec.go

towards https://github.com/giantswarm/giantswarm/issues/2971

Add collector for DeletionTimestamp metrics

---

controller/controller.go

When we renamed the framework to controller we forgot the pointer receiver.

renames pointer receiver

---

controller/integration/test/controlflow/controlflow_test.go
controller/integration/test/reconciliation/reconciliation_test.go

Towards https://github.com/giantswarm/giantswarm/issues/1595

increase wait times in backoff for integration tests

---

.circleci/config.yml
.gitignore
controller/integration/test/parallel/backoff.go
controller/integration/test/parallel/error.go
controller/integration/test/parallel/parallel_test.go

towards https://github.com/giantswarm/giantswarm/issues/1595

Add multi framework integration test for finalizers

---

controller/finalizer.go
controller/finalizer_test.go
controller/integration/test/parallel/parallel_test.go

towards https://github.com/giantswarm/giantswarm/issues/1595

Fix faulty finalizer removal to properly handle resourceVersion

---

example/memcached-operator/main.go
example/memcached-operator/memcached/memcached.go

Pawel, here is a start on the example operator. I kept it small as I'd like to check the direction is OK.

Initial setup for the example operator

---

example/memcached-operator/README.md
example/memcached-operator/controller/key/key.go
example/memcached-operator/controller/memcached.go
example/memcached-operator/controller/resource/deployments.go

It's tested, works nicely. I didn't test if memcached works. We need
services first.

example/memcached-operator: implement deployments resource

---

README.md
docs/keeping_reconciliation_loops_short.md

Towards https://github.com/giantswarm/giantswarm/issues/3196.

adds first docs for best practises

---

README.md
docs/using_finalizers.md

Towards https://github.com/giantswarm/giantswarm/issues/3196.

adds docs about finalizer usage

---

README.md
docs/control_flow_primitives.md

Towards https://github.com/giantswarm/giantswarm/issues/3196.

adds docs about control flow primitives

---

controller/resource/retryresource/wrap.go

Towards https://github.com/giantswarm/giantswarm/issues/3296.

improves default for retry resources for easier operator management

---

client/k8srestconfig/k8s_rest_config.go

While testing I discovered a situation in the `node-operator` where it got stuck completely when querying the guest cluster's Kubernetes API. I noticed the rest config we use everywhere does support a timeout setting but we are not making use of it. I hope to improve such situations with this PR. In my very case I restarted the `node-operator` and the whole update mechanism caught up and succeeded eventually. 
> // The maximum length of time to wait before giving up on a server request. 
> // A value of zero means no timeout.
> Timeout time.Duration
Also see https://godoc.org/k8s.io/client-go/rest#Config.

adds timeout setting for rest config

---

client/k8scrdclient/k8scrdclient.go

Towards https://github.com/giantswarm/giantswarm/issues/3293
Extends EnsureCreated in the CRD client to update the CRD if it has a status subresource that is not created. This happens when the CRD is already created for the cluster.

Create CRD status subresource if it is not present

---

README.md
docs/managing_cr_status_sub_resources.md
docs/troubleshooting.md

Towards https://github.com/giantswarm/giantswarm/issues/3196.

adds docs about status resources

---

controller/controller.go
controller/finalizer.go

Also keep finalizers in case handling resource set is not found.

controller: improve finalizer removal logging

---

informer/informer.go

Fixing the e2e test introduced with https://github.com/giantswarm/operatorkit/pull/245. Note this PR is also based on this branch.

fixes informer

---

.circleci/config.yml
controller/integration/test/controlflow/controlflow_test.go
controller/integration/test/parallel/parallel_test.go
informer/informer.go
informer/integration/test/basic/basic_test.go
informer/integration/test/basic/config_map.go
informer/integration/test/basic/init.go
informer/integration/test/deletionerror/config_map.go
informer/integration/test/deletionerror/deletion_error_test.go
informer/integration/test/deletionerror/error.go
informer/integration/test/deletionerror/filter_watcher.go
informer/integration/test/deletionerror/init.go

Towards https://github.com/giantswarm/giantswarm/issues/4433. Here I added a new e2e test for the informer. This test fails now and shows where the issue results into. I want to provide another PR based on this one and make the test green.

adds e2e test for informer deletion error

---

controller/integration/test/reconciliation/reconciliation_test.go
controller/integration/wrapper/configmap/crud.go
controller/integration/wrapper/nodeconfig/crud.go

Fixes https://circleci.com/gh/giantswarm/operatorkit/2617.

fixes controller e2e flapping

---

controller/controller.go
controller/integration/test/controlflow/controlflow_test.go
controller/integration/test/controlflow/error.go
controller/integration/testresource/testresource.go

Towards https://github.com/giantswarm/giantswarm/issues/4572.
Pulled parts of the changes from https://github.com/giantswarm/operatorkit/pull/260.

controlflow: fix potential races

---

controller/integration/test/parallel/error.go
controller/integration/test/parallel/parallel_test.go

Towards https://github.com/giantswarm/giantswarm/issues/4572.
Aligns with: https://github.com/giantswarm/operatorkit/pull/265.
Pulled parts of the changes from https://github.com/giantswarm/operatorkit/pull/260.

parallel: align test

---

controller/integration/test/controlflow/controlflow_test.go
controller/integration/test/parallel/parallel_test.go

Towards https://github.com/giantswarm/giantswarm/issues/4572.

controlflow, parallel: align tests

---

controller/controller.go

Follow up of https://github.com/giantswarm/operatorkit/pull/284.

controller: fix logging in case InitCtx is failing also during update

---

resource/configmap/create.go
resource/configmap/current.go
resource/configmap/delete.go
resource/configmap/desired.go
resource/configmap/error.go
resource/configmap/new_app_cr_to_update.go
resource/configmap/new_config_map_to_update.go
resource/configmap/patch.go
resource/configmap/resource.go
resource/configmap/spec.go
resource/configmap/update.go

Towards https://github.com/giantswarm/giantswarm/issues/5461.
This is mostly generated by the script below.
The only manual changes are in this commit: https://github.com/giantswarm/operatorkit/pull/288/commits/a4ae7bccb6056e943e1d62601d4133243d4b42a0.
```bash
replace() {
local a=$1; shift
local b=$1; shift
local dir=$1; shift
local a="${a//\//\\/}"
local b="${b//\//\\/}"
for file in $(find $dir \( -path ./.git -o -path ./vendor \)  -prune -o -type f -print); do
sed -i -e "s/${a}/${b}/g" $file
done
}
cp ../release-operator/pkg/controller/resource/app ./resource/configmap
replace 'package app' 'package configmap' ./resource/configmap
replace 'App CR' ConfigMap ./resource/configmap
replace 'AppCR' ConfigMap ./resource/configmap
replace 'appCR' configMap ./resource/configmap
replace …
```

resource/configmap: add

---

resource/secret/resource.go

Solving build issue in https://github.com/giantswarm/cluster-operator/pull/416

Remove unnecessary g8s client

---

Gopkg.lock
Gopkg.toml
vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
vendor/github.com/prometheus/client_golang/prometheus/http.go
vendor/github.com/prometheus/client_golang/prometheus/summary.go

...to be compatible between different libraries / dependencies.

Pin prometheus/client_golang to latest release

---

resource/crud/resource_test.go

When I wrote this I knew it is not cool and now I found how we did it in another place. This is way more elegant.

improve interface tests

---

docs/metrics_provider.md

Trying to improve the docs. I'm open to suggestions! If you think something else can be added just let me know.

Improve metrics collection docs

---

controller/controller.go
controller/resource_set.go

Following up as requested in https://github.com/giantswarm/operatorkit/pull/338#discussion_r352059785.

drop backoff factory setting

---

controller/controller.go

When booting is retried we close the booted channel twice. The elegant solution here is inspired by Mr. @tuommaki. See also https://play.golang.org/p/30DQJjNTsmD.

fix panic on boot

---

Gopkg.lock
controller/collector/error.go
controller/collector/set.go
controller/collector/spec.go
controller/collector/timestamp.go
controller/controller.go
controller/metric.go
vendor/github.com/giantswarm/exporterkit/LICENSE
vendor/github.com/giantswarm/exporterkit/collector/error.go
vendor/github.com/giantswarm/exporterkit/collector/set.go
vendor/github.com/giantswarm/exporterkit/collector/spec.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go

towards: https://github.com/giantswarm/giantswarm/issues/8077

adding timestamp collector back from informer package

---

controller/controller.go

It is not necessary to use our own mutex anymore since we use the upstream controller runtime. We explicitly set [`MaxConcurrentReconciles: 1,`](https://github.com/giantswarm/operatorkit/blob/b735498713111e430da95253eabf394e631bba09/controller/controller.go#L305).

drop mutex due to controller synchronization

---

.circleci/config.yml
CHANGELOG.md
controller/collector/set.go
resource/k8s/configmapresource/create.go
resource/k8s/configmapresource/delete.go
resource/k8s/configmapresource/update.go
resource/k8s/secretresource/create.go
resource/k8s/secretresource/delete.go
resource/k8s/secretresource/update.go
resource/wrapper/metricsresource/metrics_resource.go
resource/wrapper/retryresource/retry_resource.go

use architect orb

---

CHANGELOG.md
controller/controller.go
go.mod
integration/wrapper/drainerconfig/crud.go
integration/wrapper/drainerconfig/wrapper.go

drop CRD management

---

CHANGELOG.md
controller/collector/set.go
controller/collector/timestamp.go
controller/controller.go
go.mod
go.sum
integration/test/statusupdate/resource.go
integration/wrapper/configmap/wrapper.go
integration/wrapper/drainerconfig/wrapper.go

update go.mod file

---

controller/controller.go

This is to have a more straight forward code flow and more consistent error handling.

improve error handling

---

controller/controller.go

controller: get rid of errorCollector channel

---

CHANGELOG.md
ROADMAP.md
controller/controller.go
controller/selector.go
controller/selector_test.go

Towards https://github.com/giantswarm/giantswarm/issues/11480

controller: use local less rigid `Selector` interface

---

CHANGELOG.md
controller/controller.go
controller/selector.go

controller: use correct Selector implementation

---

.github/workflows/zz_generated.create_release.yaml
.github/workflows/zz_generated.create_release_pr.yaml

workflows: add

---

.circleci/config.yml

circleci: update architect orb to 0.9.0

---

README.md
docs/using_kubernetes_events.md

some docs improvements

---

README.md
docs/using_kubernetes_events.md

Doc for Kubernetes Events

---

integration/test/controlflow/controlflow_test.go

refactor control flow integration test

---

integration/test/parallel/parallel_test.go
integration/test/reconciliation/reconciliation_test.go
integration/test/statusupdate/status_update_test.go

Continuing effort of https://github.com/giantswarm/operatorkit/pull/442.

some more refactoring around integration tests

---

.circleci/config.yml
CHANGELOG.md
README.md
controller/controller.go
docs/control_flow_primitives.md
docs/pause_reconciliation.md
integration/test/pause/error.go
integration/test/pause/pause_test.go

Resolves https://github.com/giantswarm/giantswarm/issues/10950.

add configurable pause annotation support

---

.circleci/config.yml
go.mod
go.sum

update go and architect version

---

CHANGELOG.md
pkg/controller/controller.go

I had some panics recently because of double-closing channels. I think this resolves the problem.

fix double channel close panic

---

pkg/controller/collector/timestamp.go

https://github.com/giantswarm/kvm-operator/pull/1136#issuecomment-785149679

Switch back to UnstructuredList

---

CHANGELOG.md
go.mod
go.sum

Use k8sclient with crdclient added

---

CHANGELOG.md
pkg/controller/finalizer.go

Related discussion: https://github.com/giantswarm/cluster-apps-operator/pull/161#discussion_r800649380

Export `GetFinalizerName`
